### ISSUE TITLE
init.el 中install.el 需要修改，

### ISSUE THREAD

**Issue by kecode** [condy0919/.emacs.d#41]
https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el 
![image](https://user-images.githubusercontent.com/23140388/84766136-e2d11d80-b002-11ea-8f73-655ee4364dd6.png)
请查看这个 https://github.com/raxod502/straight.el/issues/405 已经关闭的issue

**Comment by condy0919** [comment]
它这个已经解决了。这个错误是以前 `straight.el` 少了个 `install/alpha` 分支，现在这个分支已经有了，不应当会有这个错误。

这个错误提示只要 `HTTP` `GET` 时返回的状态码不是 **200** 就会出现，先尝试`curl`一下看看

``` bash
curl -I 'https://raw.githubusercontent.com/raxod502/straight.el/install/alpha/straight.el'
```
输出的状态码是什么。

PS: `raw.githubusercontent.com` 域名是被墙的，可能需要翻墙一下

**Comment by kecode** [comment]
![image](https://user-images.githubusercontent.com/23140388/84771154-7c9cc880-b00b-11ea-97ae-131d90f5a386.png)
输出的200。我再仔细研究下你给我发的邮件。
