### ISSUE TITLE
中文输入法?

### ISSUE THREAD

**Issue by Inc0n** [condy0919/.emacs.d#94]
请问你的中文输入法有用什么吗，我之前有在用 pyim, 但是最近有些奇怪的bug.

**Comment by condy0919** [comment]
我是直接使用的系统输入法

**Comment by Inc0n** [comment]
再请问了，我看您也是有用evil，那在chinese input active的情况下，岂不会和leader keymap有些冲突，那么对于这个你也是没有什么针对性地处理吗？

**Comment by condy0919** [comment]
> 再请问了，我看您也是有用evil，那在chinese input active的情况下，岂不会和leader keymap有些冲突，那么对于这个你也是没有什么针对性地处理吗？

因为写代码的时候不会启用中文输入法，所以不怎么会有冲突。如果实在要写中文的注释，也只是会临时启用一下，然后就会关掉了。
